import "./globals.css";
import Navbar from "./components/Navbar";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
  title: "Hack Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <SpeedInsights />
      <head>
        <script
          defer
          data-website-id="67e6a3a22ac87103606b2ef1"
          data-domain="www.hackstudio.co"
          src="/js/script.js"
        ></script>
      </head>
      <body>
        <div className="lg:flex lg:flex-row h-screen">
          <Navbar />
          <div className="lg:w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
