import "./globals.css";
import Navbar from "./components/Navbar";
import TopMenu from "./components/TopMenu";
import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata = {
  title: "Hack Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <head>
        <SpeedInsights />
        <script
          defer
          data-website-id="67e6a3a22ac87103606b2ef1"
          data-domain="www.hackstudio.co"
          src="/js/script.js"
        ></script>
      </head>
      <body className="h-screen overflow-hidden">
        <div className="lg:flex lg:flex-row h-full bg-neutral">
          <div className="p-6 lg:sticky lg:top-0 lg:h-screen flex flex-col">
            <Navbar />
            <div className="flex-1" />
          </div>
          <div className="lg:w-5/6 flex flex-col gap-12 h-full overflow-y-auto">
            <TopMenu />
            <main className="flex-1">{children}</main>
          </div>
        </div>
      </body>
    </html>
  );
}
